apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: prometheus
      tracesToProfiles:
        customQuery: false
        datasourceUid: pyroscope
        profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
        tags:
          - key: service.name
            value: service_name
          - key: host.name
            value: host_name

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherType: label
          matcherRegex: trace_id
          datasourceUid: tempo
          url: '$${__value.raw}'

  - name: Pyroscope
    uid: pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: ${PYROSCOPE_URL}
    editable: false
