import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  CfnOutput,
  CfnParameter,
  Duration,
  RemovalPolicy,
  Stack,
  StackProps,
  Tags,
} from "aws-cdk-lib";
import {
  AmazonLinuxCpuType,
  BlockDeviceVolume,
  CfnInstance,
  Instance,
  InstanceType,
  IpAddresses,
  MachineImage,
  Port,
  SecurityGroup,
  SubnetType,
  UserData,
  Vpc,
} from "aws-cdk-lib/aws-ec2";
import { DockerImageAsset, Platform } from "aws-cdk-lib/aws-ecr-assets";
import { ManagedPolicy, Role, ServicePrincipal } from "aws-cdk-lib/aws-iam";
import { Construct } from "constructs";

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(currentDirectory, "../../..");
const PRIVATE_IPS = {
  loadgen: "10.42.0.10",
  ssp: "10.42.0.20",
  dsp: "10.42.0.30",
  support: "10.42.0.40",
  observer: "10.42.0.50",
} as const;
const OTEL_COLLECTOR_IMAGE = "otel/opentelemetry-collector-contrib:0.159.0";
const PROMETHEUS_IMAGE = "prom/prometheus:v3.14.0";
const TEMPO_IMAGE = "grafana/tempo:3.0.3";
const LOKI_IMAGE = "grafana/loki:3.7.7";
const GRAFANA_IMAGE = "grafana/grafana:13.2.0";

export interface Stage8cStackProps extends StackProps {
  readonly instanceType?: string;
}

export class Stage8cStack extends Stack {
  constructor(scope: Construct, id: string, props: Stage8cStackProps = {}) {
    super(scope, id, props);

    const databasePassword = new CfnParameter(this, "DatabasePassword", {
      type: "String",
      noEcho: true,
      minLength: 24,
      description: "Ephemeral PostgreSQL password generated by the deployment runner.",
    });
    const instanceType = new InstanceType(props.instanceType ?? "t4g.small");
    const vpc = new Vpc(this, "ExperimentVpc", {
      ipAddresses: IpAddresses.cidr("10.42.0.0/16"),
      maxAzs: 1,
      natGateways: 0,
      subnetConfiguration: [{
        name: "experiment-public",
        subnetType: SubnetType.PUBLIC,
        cidrMask: 24,
      }],
    });

    const loadgenSecurityGroup = new SecurityGroup(this, "LoadgenSecurityGroup", { vpc });
    const sspSecurityGroup = new SecurityGroup(this, "SspSecurityGroup", { vpc });
    const dspSecurityGroup = new SecurityGroup(this, "DspSecurityGroup", { vpc });
    const supportSecurityGroup = new SecurityGroup(this, "SupportSecurityGroup", { vpc });
    const observerSecurityGroup = new SecurityGroup(this, "ObserverSecurityGroup", { vpc });

    sspSecurityGroup.addIngressRule(loadgenSecurityGroup, Port.tcp(8080), "k6 to SSP");
    supportSecurityGroup.addIngressRule(sspSecurityGroup, Port.tcpRange(8080, 8082), "SSP to DSP fixtures");
    supportSecurityGroup.addIngressRule(sspSecurityGroup, Port.tcp(5432), "SSP store");
    supportSecurityGroup.addIngressRule(dspSecurityGroup, Port.tcpRange(5433, 5434), "DSP stores");
    dspSecurityGroup.addIngressRule(supportSecurityGroup, Port.tcp(8081), "authenticated gateway to DSP");
    for (const [source, description] of [
      [loadgenSecurityGroup, "loadgen"],
      [sspSecurityGroup, "SSP"],
      [dspSecurityGroup, "DSP"],
      [supportSecurityGroup, "support"],
    ] as const) {
      observerSecurityGroup.addIngressRule(source, Port.tcp(4317), `${description} traces to Tempo`);
      observerSecurityGroup.addIngressRule(source, Port.tcp(3100), `${description} logs to Loki`);
      source.addIngressRule(observerSecurityGroup, Port.tcp(9464), `Prometheus scrapes ${description}`);
    }

    const sspImage = new DockerImageAsset(this, "SspImage", {
      directory: repositoryRoot,
      file: "Dockerfile",
      buildArgs: { APP_MODULE: "ssp-app" },
      platform: Platform.LINUX_ARM64,
    });
    const dspImage = new DockerImageAsset(this, "DspImage", {
      directory: repositoryRoot,
      file: "Dockerfile",
      buildArgs: { APP_MODULE: "dsp-app" },
      platform: Platform.LINUX_ARM64,
    });
    const supportImage = new DockerImageAsset(this, "SupportImage", {
      directory: repositoryRoot,
      file: "performance/fixtures/stage8c/Dockerfile",
      platform: Platform.LINUX_ARM64,
    });
    const observabilityImage = new DockerImageAsset(this, "ObservabilityImage", {
      directory: path.join(repositoryRoot, "observability"),
      file: "Dockerfile",
      platform: Platform.LINUX_ARM64,
    });

    const loadgen = this.createHost(
      "Loadgen", vpc, instanceType, loadgenSecurityGroup, PRIVATE_IPS.loadgen, 16);
    const ssp = this.createHost(
      "Ssp", vpc, instanceType, sspSecurityGroup, PRIVATE_IPS.ssp, 16);
    const dsp = this.createHost(
      "Dsp", vpc, instanceType, dspSecurityGroup, PRIVATE_IPS.dsp, 16);
    const support = this.createHost(
      "Support", vpc, instanceType, supportSecurityGroup, PRIVATE_IPS.support, 24);
    const observer = this.createHost(
      "Observer", vpc, instanceType, observerSecurityGroup, PRIVATE_IPS.observer, 24);

    supportImage.repository.grantPull(loadgen.role);
    sspImage.repository.grantPull(ssp.role);
    dspImage.repository.grantPull(dsp.role);
    supportImage.repository.grantPull(support.role);
    for (const host of [loadgen, ssp, dsp, support, observer]) {
      observabilityImage.repository.grantPull(host.role);
    }

    this.addRegistryLogin(loadgen.instance.userData);
    this.addRegistryLogin(ssp.instance.userData);
    this.addRegistryLogin(dsp.instance.userData);
    this.addRegistryLogin(support.instance.userData);
    this.addRegistryLogin(observer.instance.userData);

    this.configureCollector(
      loadgen.instance.userData, observabilityImage.imageUri, "loadgen", PRIVATE_IPS.observer);
    this.configureCollector(
      ssp.instance.userData, observabilityImage.imageUri, "ssp", PRIVATE_IPS.observer);
    this.configureCollector(
      dsp.instance.userData, observabilityImage.imageUri, "dsp", PRIVATE_IPS.observer);
    this.configureCollector(
      support.instance.userData, observabilityImage.imageUri, "support", PRIVATE_IPS.observer);
    this.configureObserver(
      observer.instance.userData, observabilityImage.imageUri, PRIVATE_IPS.observer);

    this.configureSupport(
      support.instance.userData,
      supportImage.imageUri,
      PRIVATE_IPS.dsp,
      PRIVATE_IPS.support,
      databasePassword.valueAsString,
    );
    this.configureDsp(
      dsp.instance.userData,
      dspImage.imageUri,
      PRIVATE_IPS.support,
      databasePassword.valueAsString,
    );
    this.configureSsp(
      ssp.instance.userData,
      sspImage.imageUri,
      PRIVATE_IPS.ssp,
      PRIVATE_IPS.support,
      databasePassword.valueAsString,
    );
    this.configureLoadgen(loadgen.instance.userData, supportImage.imageUri);

    this.outputHost("Loadgen", loadgen.instance);
    this.outputHost("Ssp", ssp.instance);
    this.outputHost("Dsp", dsp.instance);
    this.outputHost("Support", support.instance);
    this.outputHost("Observer", observer.instance);
    new CfnOutput(this, "SspBaseUrl", {
      value: `http://${PRIVATE_IPS.ssp}:8080`,
    });
    new CfnOutput(this, "Topology", {
      value: "loadgen -> ssp -> support(gateway,external-a,external-b) -> dsp; ssp,dsp -> support(postgres x3); all hosts -> observer",
    });

    Tags.of(this).add("Project", "low-latency-rtb");
    Tags.of(this).add("Stage", "8c");
    Tags.of(this).add("Environment", "ephemeral-performance");
  }

  private createHost(
    name: string,
    vpc: Vpc,
    instanceType: InstanceType,
    securityGroup: SecurityGroup,
    privateIpAddress: string,
    volumeGiB: number,
  ): { instance: Instance; role: Role } {
    const role = new Role(this, `${name}Role`, {
      assumedBy: new ServicePrincipal("ec2.amazonaws.com"),
      managedPolicies: [
        ManagedPolicy.fromAwsManagedPolicyName("AmazonSSMManagedInstanceCore"),
      ],
    });
    const userData = UserData.forLinux();
    userData.addCommands(
      "set -euxo pipefail",
      "dnf install -y docker openssl",
      "systemctl enable --now docker",
      "mkdir -p /opt/rtb",
    );
    const instance = new Instance(this, `${name}Instance`, {
      vpc,
      vpcSubnets: { subnetType: SubnetType.PUBLIC },
      associatePublicIpAddress: true,
      privateIpAddress,
      instanceType,
      machineImage: MachineImage.latestAmazonLinux2023({
        cpuType: AmazonLinuxCpuType.ARM_64,
      }),
      securityGroup,
      role,
      userData,
      requireImdsv2: true,
      blockDevices: [{
        deviceName: "/dev/xvda",
        volume: BlockDeviceVolume.ebs(volumeGiB, {
          encrypted: true,
          deleteOnTermination: true,
        }),
      }],
    });
    instance.applyRemovalPolicy(RemovalPolicy.DESTROY);
    const cfnInstance = instance.node.defaultChild as CfnInstance;
    cfnInstance.creditSpecification = { cpuCredits: "standard" };
    return { instance, role };
  }

  private addRegistryLogin(userData: UserData): void {
    userData.addCommands(
      `aws ecr get-login-password --region ${this.region} | docker login --username AWS --password-stdin ${this.account}.dkr.ecr.${this.region}.amazonaws.com`,
    );
  }

  private configureCollector(
    userData: UserData,
    observabilityImage: string,
    hostRole: string,
    observerPrivateIp: string,
  ): void {
    userData.addCommands(
      `docker pull ${observabilityImage}`,
      `docker create --name observability-assets ${observabilityImage}`,
      "docker cp observability-assets:/opt/observability /opt/rtb/observability",
      "docker rm observability-assets",
      `docker pull ${OTEL_COLLECTOR_IMAGE}`,
      `docker run -d --name otel-collector --restart unless-stopped --network host --pid host -v /:/hostfs:ro -v /opt/rtb/observability/collector/agent.yaml:/etc/otelcol-contrib/agent.yaml:ro -e HOST_ROLE=${hostRole} -e DEPLOYMENT_ENVIRONMENT=aws-stage8c -e TEMPO_OTLP_ENDPOINT=${observerPrivateIp}:4317 -e LOKI_OTLP_ENDPOINT=http://${observerPrivateIp}:3100/otlp ${OTEL_COLLECTOR_IMAGE} --config=/etc/otelcol-contrib/agent.yaml`,
    );
  }

  private configureObserver(
    userData: UserData,
    observabilityImage: string,
    observerPrivateIp: string,
  ): void {
    this.configureCollector(userData, observabilityImage, "observer", observerPrivateIp);
    userData.addCommands(
      "mkdir -p /opt/rtb/tempo-data /opt/rtb/loki-data /opt/rtb/prometheus-data /opt/rtb/grafana-data",
      "chmod 0777 /opt/rtb/tempo-data /opt/rtb/loki-data /opt/rtb/prometheus-data /opt/rtb/grafana-data",
      `docker pull ${TEMPO_IMAGE}`,
      `docker run -d --name tempo --restart unless-stopped --network host -v /opt/rtb/observability/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro -v /opt/rtb/tempo-data:/var/tempo ${TEMPO_IMAGE} -config.file=/etc/tempo/tempo.yaml`,
      `docker pull ${LOKI_IMAGE}`,
      `docker run -d --name loki --restart unless-stopped --network host -v /opt/rtb/observability/loki/loki.yaml:/etc/loki/loki.yaml:ro -v /opt/rtb/loki-data:/var/loki ${LOKI_IMAGE} -config.file=/etc/loki/loki.yaml`,
      `docker pull ${PROMETHEUS_IMAGE}`,
      `docker run -d --name prometheus --restart unless-stopped --network host -v /opt/rtb/observability/prometheus/aws-stage8c.yaml:/etc/prometheus/prometheus.yml:ro -v /opt/rtb/prometheus-data:/prometheus ${PROMETHEUS_IMAGE} --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=24h`,
      `docker pull ${GRAFANA_IMAGE}`,
      `docker run -d --name grafana --restart unless-stopped --network host -v /opt/rtb/observability/grafana/provisioning:/etc/grafana/provisioning:ro -v /opt/rtb/grafana-data:/var/lib/grafana -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer -e GF_AUTH_DISABLE_LOGIN_FORM=true -e PROMETHEUS_URL=http://127.0.0.1:9090 -e TEMPO_URL=http://127.0.0.1:3200 -e LOKI_URL=http://127.0.0.1:3100 ${GRAFANA_IMAGE}`,
    );
  }

  private configureLoadgen(userData: UserData, supportImage: string): void {
    userData.addCommands(
      `docker pull ${supportImage}`,
      `docker create --name stage8c-assets ${supportImage}`,
      "docker cp stage8c-assets:/opt/stage8c/k6 /opt/rtb/k6",
      "docker cp stage8c-assets:/opt/stage8c/aws-vm-baseline.sh /opt/rtb/aws-vm-baseline.sh",
      "docker rm stage8c-assets",
      "chmod +x /opt/rtb/aws-vm-baseline.sh",
      "docker pull grafana/k6:1.2.1",
    );
  }

  private configureSupport(
    userData: UserData,
    supportImage: string,
    dspPrivateIp: string,
    supportPrivateIp: string,
    databasePassword: string,
  ): void {
    userData.addCommands(
      `docker pull ${supportImage}`,
      `docker create --name stage8c-assets ${supportImage}`,
      "docker cp stage8c-assets:/opt/stage8c/init /opt/rtb/init",
      "docker cp stage8c-assets:/opt/stage8c/aws-vm-baseline.sh /opt/rtb/aws-vm-baseline.sh",
      "docker rm stage8c-assets",
      "chmod +x /opt/rtb/aws-vm-baseline.sh",
      "docker pull postgres:17-alpine",
      this.postgresRun("provider-store", 5432, "/opt/rtb/init/provider", databasePassword),
      this.postgresRun("ledger-store", 5433, "/opt/rtb/init/ledger", databasePassword),
      this.postgresRun("outcome-store", 5434, "/opt/rtb/init/outcome", databasePassword),
      `docker run -d --name stage8c-support --restart unless-stopped --network host -e DSP_BASE_URL=http://${dspPrivateIp}:8081 -e SUPPORT_PRIVATE_IP=${supportPrivateIp} ${supportImage}`,
    );
  }

  private postgresRun(
    name: string,
    port: number,
    initDirectory: string,
    password: string,
  ): string {
    return `docker run -d --name ${name} --restart unless-stopped -p ${port}:5432 -e POSTGRES_DB=rtb -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD='${password}' -v ${name}-data:/var/lib/postgresql/data -v ${initDirectory}:/docker-entrypoint-initdb.d:ro postgres:17-alpine -c max_connections=80 -c shared_buffers=128MB`;
  }

  private configureDsp(
    userData: UserData,
    dspImage: string,
    supportPrivateIp: string,
    databasePassword: string,
  ): void {
    userData.addCommands(
      `docker pull ${dspImage}`,
      "until timeout 1 bash -c '</dev/tcp/" + supportPrivateIp + "/5433'; do sleep 2; done",
      "STARTS_AT=$(date -u -d '-5 minutes' +%Y-%m-%dT%H:%M:%SZ)",
      "ENDS_AT=$(date -u -d '+7 days' +%Y-%m-%dT%H:%M:%SZ)",
      "printf '{\"version\":\"v1\",\"campaigns\":[{\"id\":\"campaign-1\",\"active\":true,\"bidCpmMilliKrw\":2000,\"startsAt\":\"%s\",\"endsAt\":\"%s\",\"creatives\":[{\"id\":\"creative-1\",\"width\":300,\"height\":250}]}]}\n' \"$STARTS_AT\" \"$ENDS_AT\" > /opt/rtb/campaigns.json",
      "CAMPAIGN_SHA=$(sha256sum /opt/rtb/campaigns.json | cut -d' ' -f1)",
      "NOTICE_KEY=$(openssl rand -base64 32 | tr -d '\\n')",
      `docker run -d --name dsp --restart unless-stopped --network host -v /opt/rtb/campaigns.json:/opt/rtb/campaigns.json:ro ${this.otelJavaEnvironment("rtb-dsp")} -e JAVA_TOOL_OPTIONS='-Xms768m -Xmx768m -XX:+UseG1GC -javaagent:/otel/opentelemetry-javaagent.jar' -e SERVER_PORT=8081 -e DSP_REGION_ID=${this.region} -e DSP_INSTANCE_ID=dsp-stage8c-1 -e DSP_PUBLIC_BASE_URL=http://${supportPrivateIp}:8080 -e DSP_CAMPAIGN_SNAPSHOT_PATH=/opt/rtb/campaigns.json -e DSP_CAMPAIGN_VERSION=v1 -e DSP_CAMPAIGN_SHA256=\"$CAMPAIGN_SHA\" -e DSP_NOTICE_TOKEN_ACTIVE_KEY_ID=key-1 -e DSP_NOTICE_TOKEN_KEYS=key-1=\"$NOTICE_KEY\" -e DSP_LEDGER_JDBC_URL=jdbc:postgresql://${supportPrivateIp}:5433/rtb -e DSP_OUTCOME_JDBC_URL=jdbc:postgresql://${supportPrivateIp}:5434/rtb -e DSP_STORE_USERNAME=postgres -e DSP_STORE_PASSWORD='${databasePassword}' -e DSP_BID_WORKERS=8 -e DSP_NOTICE_WORKERS=4 -e DSP_LEDGER_POOL_SIZE=6 -e DSP_OUTCOME_POOL_SIZE=6 -e DSP_JDBC_WORKERS=6 ${dspImage}`,
    );
  }

  private configureSsp(
    userData: UserData,
    sspImage: string,
    sspPrivateIp: string,
    supportPrivateIp: string,
    databasePassword: string,
  ): void {
    const endpoints = [
      `project-dsp=http://${supportPrivateIp}:8080/openrtb/2.6/bid`,
      `external-a=http://${supportPrivateIp}:8081/openrtb/2.6/bid`,
      `external-b=http://${supportPrivateIp}:8082/openrtb/2.6/bid`,
    ].join(",");
    userData.addCommands(
      `docker pull ${sspImage}`,
      "until timeout 1 bash -c '</dev/tcp/" + supportPrivateIp + "/5432'; do sleep 2; done",
      "RENDER_KEY=$(openssl rand -base64 32 | tr -d '\\n')",
      `docker run -d --name ssp --restart unless-stopped --network host ${this.otelJavaEnvironment("rtb-ssp")} -e JAVA_TOOL_OPTIONS='-Xms768m -Xmx768m -XX:+UseG1GC -javaagent:/otel/opentelemetry-javaagent.jar' -e SERVER_PORT=8080 -e SSP_REGION_ID=${this.region} -e RENDER_COMPLETION_URL=http://${sspPrivateIp}:8080/publisher/render -e DATABASE_URL=jdbc:postgresql://${supportPrivateIp}:5432/rtb -e DATABASE_USERNAME=postgres -e DATABASE_PASSWORD='${databasePassword}' -e RENDER_PROOF_KEY_BASE64=\"$RENDER_KEY\" -e DSP_ENDPOINTS='${endpoints}' -e PROVIDER_MAX_IN_FLIGHT=128 -e DSP_BID_TIMEOUT_MS=100 -e DSP_MAX_IN_FLIGHT=256 -e BILLING_WORKER_CONCURRENCY=8 ${sspImage}`,
    );
  }

  private otelJavaEnvironment(serviceName: string): string {
    return [
      `-e OTEL_SERVICE_NAME=${serviceName}`,
      "-e OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4318",
      "-e OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf",
      "-e OTEL_TRACES_EXPORTER=otlp",
      "-e OTEL_METRICS_EXPORTER=otlp",
      "-e OTEL_LOGS_EXPORTER=otlp",
      "-e OTEL_PROPAGATORS=tracecontext,baggage",
      "-e OTEL_TRACES_SAMPLER=parentbased_traceidratio",
      "-e OTEL_TRACES_SAMPLER_ARG=0.10",
      "-e OTEL_METRIC_EXPORT_INTERVAL=5000",
      "-e OTEL_BSP_SCHEDULE_DELAY=1000",
      "-e OTEL_RESOURCE_ATTRIBUTES=service.namespace=rtb,deployment.environment.name=aws-stage8c,service.version=0.1.0-SNAPSHOT",
    ].join(" ");
  }

  private outputHost(name: string, instance: Instance): void {
    new CfnOutput(this, `${name}InstanceId`, { value: instance.instanceId });
    new CfnOutput(this, `${name}PrivateIp`, { value: instance.instancePrivateIp });
  }
}
